### ISSUE TITLE
Can RN use all of Lokka?

### ISSUE THREAD

**Issue by AdamBrodzinski** [kadira-samples/react-native-graphql-demo#1]
I was browsing the source and was wondering if you can use all the fragments and cache features from Lokka with React Native? Since Relay doesn't work I wasn't sure if it was related.

Thanks!!

**Comment by arunoda** [comment]
Yeah! You use.
Lokka is a fully JS and does not depend on React.
You can use react-komposer with it.

**Comment by AdamBrodzinski** [comment]
Awesome, thanks!
